Repository XanaduAI/jet, pull requests merged in 2021-08, with the labels that each got.

#59 Prepare for 0.2.1 release
  .github/CHANGELOG.md
  README.rst
  docs/dev/research.rst
  docs/index.rst
  include/jet/CudaTensorHelpers.hpp
Labels: documentation 📚

#54 Mutators for populating XIR programs
  python/tests/xir/test_io.py
  python/tests/xir/test_program.py
  python/xir/interfaces/strawberryfields_io.py
  python/xir/parser.py
  python/xir/program.py
Labels: enhancement ✨

#64 Use PyLint
  .github/CHANGELOG.md
  python/.pylintrc
  python/Makefile
  python/jet/__init__.py
  python/jet/circuit.py
  python/jet/factory.py
  python/jet/gate.py
  python/jet/interpreter.py
  python/jet/state.py
  python/requirements.txt
  python/tests/jet/conftest.py
  python/tests/jet/test_circuit.py
  python/tests/jet/test_gate.py
  python/tests/jet/test_interpreter.py
  python/tests/jet/test_pathinfo.py
  python/tests/jet/test_state.py
  python/tests/jet/test_tensor.py
  python/tests/jet/test_tensor_network.py
  python/tests/xir/test_decimal_complex.py
  python/tests/xir/test_io.py
  python/tests/xir/test_program.py
  python/xir/decimal_complex.py
  python/xir/interfaces/strawberryfields_io.py
  python/xir/parser.py
  python/xir/program.py
  python/xir/utils.py
Labels: code quality 🎓

#60 Merging of XIR programs
  .github/CHANGELOG.md
  python/.pylintrc
  python/jet/interpreter.py
  python/tests/xir/test_program.py
  python/xir/program.py
Labels: enhancement ✨

#63 Resolve XIR program includes
  python/Makefile
  python/tests/xir/test_program.py
  python/xir/program.py
Labels: enhancement ✨

#61 Better declarations
  python/tests/jet/test_interpreter.py
  python/tests/xir/test_integration.py
  python/tests/xir/test_io.py
  python/tests/xir/test_parser.py
  python/tests/xir/test_program.py
  python/tests/xir/test_utils.py
  python/xir/__init__.py
  python/xir/interfaces/strawberryfields_io.py
  python/xir/ir.lark
  python/xir/parser.py
  python/xir/program.py
Labels: enhancement ✨

#66 Pip install from GitHub repository
  .github/CHANGELOG.md
  README.rst
  docs/conf.py
  include/jet/Version.hpp
  python/xir/interfaces/strawberryfields_io.py
  python/xir/program.py
  setup.py
Labels: documentation 📚
